IF OBJECT_ID('MATERIA_CARRERA') IS NOT NULL
	DROP TABLE MATERIA_CARRERA
GO
IF OBJECT_ID('BLOQUEO_MATERIA') IS NOT NULL
DROP TABLE BLOQUEO_MATERIA
GO
IF OBJECT_ID('MAESTRO_MATERIA') IS NOT NULL
DROP TABLE MAESTRO_MATERIA
GO
IF OBJECT_ID('HORARIO_GRUPO') IS NOT NULL
DROP TABLE HORARIO_GRUPO
GO
IF OBJECT_ID('ALUMNO_GRUPO') IS NOT NULL
DROP TABLE ALUMNO_GRUPO
GO

IF OBJECT_ID('GRUPO') IS NOT NULL
DROP TABLE GRUPO
GO
IF OBJECT_ID('AULA') IS NOT NULL
DROP TABLE AULA
GO
IF OBJECT_ID('HORARIO') IS NOT NULL
DROP TABLE HORARIO
GO
IF OBJECT_ID('MAESTRO') IS NOT NULL
DROP TABLE MAESTRO
GO
IF OBJECT_ID('ALUMNO') IS NOT NULL
DROP TABLE ALUMNO
GO
IF OBJECT_ID('PAIS') IS NOT NULL
DROP TABLE PAIS
GO
IF OBJECT_ID('MATERIA') IS NOT NULL
DROP TABLE MATERIA
GO
IF OBJECT_ID('COORDINADOR') IS NOT NULL
DROP TABLE COORDINADOR
GO
IF OBJECT_ID('CARRERA') IS NOT NULL
DROP TABLE CARRERA
GO
IF OBJECT_ID('SEMESTRE') IS NOT NULL
DROP TABLE SEMESTRE
GO

CREATE TABLE PAIS(
	id INT PRIMARY KEY IDENTITY(0,1),
	nombre	VARCHAR(50) NOT NULL
)
INSERT INTO PAIS(nombre) VALUES('México')
INSERT INTO PAIS(nombre) VALUES('Estados Unidos')
INSERT INTO PAIS(nombre) VALUES('Chile')
INSERT INTO PAIS(nombre) VALUES('Japón')

CREATE TABLE SEMESTRE(
id				INT			PRIMARY KEY IDENTITY(0,1),
fecha_Inicio	DATE		NOT NULL,
fecha_fin		DATE		NULL,
creditos_Min	SMALLINT	DEFAULT(1) NOT NULL,
creditos_Max	SMALLINT	NULL,
estado			BIT			DEFAULT(1) NOT NULL,
)

CREATE TABLE CARRERA(
clave			INT				PRIMARY KEY IDENTITY(500,1),
nombre			VARCHAR(50)     NOT NULL UNIQUE,
alias			VARCHAR(25)		NULL UNIQUE,
descripcion		VARCHAR(255)	NULL,
)

CREATE TABLE COORDINADOR(
clave_Usuario	VARCHAR(50)		PRIMARY KEY,
contraseña		VARCHAR(50)		NOT NULL,
num_nomina		VARCHAR(25)		NOT NULL,
nombre			VARCHAR(25)		NOT NULL,
apellido_Pat	VARCHAR(25)		NOT NULL,
apellido_Mat	VARCHAR(25)		NOT NULL,
titulo			VARCHAR(50)		NULL,
genero			BIT				DEFAULT(1),
fecha_Naci		DATE			NULL,

carrera_fk		INT				NULL,
CONSTRAINT FK_CARRERA_COORDINADA FOREIGN KEY(carrera_fk) REFERENCES CARRERA(clave)
)
insert into COORDINADOR(nombre,apellido_Pat,apellido_Mat,fecha_Naci,genero,clave_Usuario,contraseña,titulo,carrera_fk,num_nomina)
			VALUES('Gabriel','Aguirre','González',GETDATE(),1,'Admin123','1887916','Administrador/a',NULL,'0000000');

CREATE TABLE MATERIA(
clave				INT				PRIMARY KEY IDENTITY(100,1),
nombre				VARCHAR(50)		NOT NULL UNIQUE,
alias				VARCHAR(25)		NOT NULL UNIQUE,
descripcion			VARCHAR(255)	NULL,
creditos			SMALLINT		DEFAULT(1) NOT NULL,
medias_horas_Sem	SMALLINT		DEFAULT(1) NOT NULL,
nivel				TINYINT			DEFAULT(1) NOT NULL
)
--ALTER TABLE MATERIA ALTER COLUMN nombre VARCHAR(50);

CREATE TABLE ALUMNO(
matricula		INT				PRIMARY KEY IDENTITY(1000000,1),
nombre			VARCHAR(25)		NOT NULL,
apellido_Pat	VARCHAR(25)		NOT NULL,
apellido_Mat	VARCHAR(25)		NOT NULL,
genero			BIT				DEFAULT(1),
fecha_Naci		DATE			NULL,
activo			BIT				DEFAULT(1),

carrera_fk		INT				NOT NULL,
pais_fk		INT				NOT NULL,
CONSTRAINT FK_CARRERA FOREIGN KEY(carrera_fk) REFERENCES CARRERA(clave),
CONSTRAINT FK_PAIS FOREIGN KEY(pais_fk) REFERENCES PAIS(id)
)
--ALTER TABLE ALUMNO ADD activo BIT default(1);

CREATE TABLE MAESTRO(
matricula		INT				PRIMARY KEY IDENTITY(10000,1),
num_nomina		VARCHAR(25)		NOT NULL,
nombre			VARCHAR(25)		NOT NULL,
apellido_Pat	VARCHAR(25)		NOT NULL,
apellido_Mat	VARCHAR(25)		NOT NULL,
genero			BIT				DEFAULT(1),
fecha_Naci		DATE			NULL,
titulo			VARCHAR(50)		NULL,
)

CREATE TABLE HORARIO(
id			INT		PRIMARY KEY IDENTITY(0,1),
hora		TIME	NOT NULL,
lunes		BIT		DEFAULT(0),
martes		BIT		DEFAULT(0),
miercoles	BIT		DEFAULT(0),
jueves		BIT		DEFAULT(0),
viernes		BIT		DEFAULT(0),
sabado		BIT		DEFAULT(0)
)--Entidad Debil para GRUPO

CREATE TABLE AULA(
id				INT				PRIMARY KEY IDENTITY(0,1),
cupo			INT				NOT NULL,
localizacion	VARCHAR(255)	NULL
)--Entidad Debil para GRUPO
INSERT INTO AULA(cupo,localizacion) VALUES(10,'Ejemplo');

CREATE TABLE GRUPO(
id			INT		PRIMARY KEY IDENTITY(0,1),
materia_fk	INT		NOT NULL,
maestro_fk	INT		NOT NULL,
aula_fk		INT		NOT NULL,
semestre_fk	INT		NOT NULL,
CONSTRAINT FK_AULA FOREIGN KEY(aula_fk) REFERENCES AULA(id),
CONSTRAINT FK_MAESTRO FOREIGN KEY(maestro_fk) REFERENCES MAESTRO(matricula),
CONSTRAINT FK_MATERIA FOREIGN KEY(materia_fk) REFERENCES MATERIA(clave),
CONSTRAINT FK_SEMESTRE_INICIO FOREIGN KEY(semestre_fk) REFERENCES SEMESTRE(id)
)

--Tablas Relacionales
CREATE TABLE MATERIA_CARRERA(
id			INT		PRIMARY KEY IDENTITY(0,1),
carrera_fk		INT				NOT NULL,
materia_fk		INT				NOT NULL,
CONSTRAINT FK_CARRERA_ESTUDIA FOREIGN KEY(carrera_fk) REFERENCES CARRERA(clave),
CONSTRAINT FK_MATERIA_ESTUDIADA FOREIGN KEY(materia_fk) REFERENCES MATERIA(clave)
)

CREATE TABLE BLOQUEO_MATERIA(
id				INT		PRIMARY KEY IDENTITY(0,1),
bloque_fk		INT				NOT NULL,
materia_fk		INT				NOT NULL,
CONSTRAINT FK_MATERIA_BLOQUEADORA FOREIGN KEY(bloque_fk) REFERENCES MATERIA(clave),
CONSTRAINT FK_MATERIA_BLOQUEADA FOREIGN KEY(materia_fk) REFERENCES MATERIA(clave)
)

CREATE TABLE MAESTRO_MATERIA(
id				INT		PRIMARY KEY IDENTITY(0,1),
maestro_fk		INT				NOT NULL,
materia_fk		INT				NOT NULL,
CONSTRAINT FK_MAESTRO_ENSEÑANTE FOREIGN KEY(maestro_fk) REFERENCES MAESTRO(matricula),
CONSTRAINT FK_MATERIA_ENSEÑADA FOREIGN KEY(materia_fk) REFERENCES MATERIA(clave)
)

CREATE TABLE HORARIO_GRUPO(
id					INT		PRIMARY KEY IDENTITY(0,1),
grupo_fk			INT				NOT NULL,
horario_fk			INT				NOT NULL,
CONSTRAINT FK_GRUPO FOREIGN KEY(grupo_fk) REFERENCES GRUPO(id),
CONSTRAINT FK_HORARIO FOREIGN KEY(horario_fk) REFERENCES HORARIO(id)
)

CREATE TABLE ALUMNO_GRUPO(
id					INT		PRIMARY KEY IDENTITY(0,1),
calificacion		FLOAT			NULL,
fecha_calif			DATE			NULL,
grupo_fk			INT				NOT NULL,
alumno_fk			INT				NOT NULL,
CONSTRAINT FK_GRUPO_INSCRITO FOREIGN KEY(grupo_fk) REFERENCES GRUPO(id),
CONSTRAINT FK_ALUMNO_INSCRITO FOREIGN KEY(alumno_fk) REFERENCES ALUMNO(matricula)
)

--------Backup tables---------
IF OBJECT_ID('PAIS_BKP') IS NOT NULL
	DROP TABLE PAIS_BKP
GO
CREATE TABLE PAIS_BKP(
	id_bkp INT PRIMARY KEY IDENTITY(0,1),
	fecha_bkp	DATE	DEFAULT(GETDATE()),
	id		INT			NOT NULL,
	nombre	VARCHAR(50) NOT NULL
)

/*IF OBJECT_ID('SEMESTRE_BKP') IS NOT NULL
	DROP TABLE SEMESTRE_BKP
GO
CREATE TABLE SEMESTRE_BKP(
	id_bkp			INT			PRIMARY KEY IDENTITY(0,1),
	fecha_bkp		DATE		DEFAULT(GETDATE()),
	id				INT			NOT NULL,
	fecha_Inicio	DATE		NOT NULL,
	fecha_fin		DATE		NULL,
	creditos_Min	SMALLINT	DEFAULT(1) NOT NULL,
	creditos_Max	SMALLINT	NULL,
	estado			BIT			DEFAULT(1) NOT NULL,
)*/

IF OBJECT_ID('CARRERA_BKP') IS NOT NULL
	DROP TABLE CARRERA_BKP
GO
CREATE TABLE CARRERA_BKP(
	id_bkp			INT				PRIMARY KEY IDENTITY(0,1),
	fecha_bkp		DATE			DEFAULT(GETDATE()),
	clave			INT				NOT NULL,
	nombre			VARCHAR(50)     NOT NULL,
	alias			VARCHAR(25)		NULL,
	descripcion		VARCHAR(255)	NULL,
)

IF OBJECT_ID('COORDINADOR_BKP') IS NOT NULL
	DROP TABLE COORDINADOR_BKP
GO
CREATE TABLE COORDINADOR_BKP(
	id_bkp			INT PRIMARY		KEY IDENTITY(0,1),
	fecha_bkp		DATE			DEFAULT(GETDATE()),
	clave_Usuario	VARCHAR(50)		NOT NULL,
	contraseña		VARCHAR(50)		NOT NULL,
	num_nomina		VARCHAR(25)		NOT NULL,
	nombre			VARCHAR(25)		NOT NULL,
	apellido_Pat	VARCHAR(25)		NOT NULL,
	apellido_Mat	VARCHAR(25)		NOT NULL,
	titulo			VARCHAR(50)		NULL,
	genero			BIT				DEFAULT(1),
	fecha_Naci		DATE			NULL,

	carrera_fk		INT				NULL
)

IF OBJECT_ID('MATERIA_BKP') IS NOT NULL
	DROP TABLE MATERIA_BKP
GO

IF OBJECT_ID('MATERIA_BKP') IS NOT NULL
	DROP TABLE MATERIA_BKP
GO
CREATE TABLE MATERIA_BKP(
	id_bkp				INT				PRIMARY KEY IDENTITY(0,1),
	fecha_bkp			DATE			DEFAULT(GETDATE()),
	clave				INT				NOT NULL,
	nombre				VARCHAR(50)		NOT NULL,
	alias				VARCHAR(25)		NOT NULL,
	descripcion			VARCHAR(255)	NULL,
	creditos			SMALLINT		DEFAULT(1) NOT NULL,
	medias_horas_Sem	SMALLINT		DEFAULT(1) NOT NULL,
	nivel				TINYINT			DEFAULT(1) NOT NULL
)

IF OBJECT_ID('ALUMNO_BKP') IS NOT NULL
	DROP TABLE ALUMNO_BKP
GO
CREATE TABLE ALUMNO_BKP(
	id_bkp			INT				PRIMARY KEY IDENTITY(0,1),
	fecha_bkp		DATE			DEFAULT(GETDATE()),
	matricula		INT				NOT NULL,
	nombre			VARCHAR(25)		NOT NULL,
	apellido_Pat	VARCHAR(25)		NOT NULL,
	apellido_Mat	VARCHAR(25)		NOT NULL,
	genero			BIT				DEFAULT(1),
	fecha_Naci		DATE			NULL,
	activo			BIT				DEFAULT(1),

	carrera_fk		INT				NOT NULL,
	pais_fk			INT				NOT NULL
)

IF OBJECT_ID('MAESTRO_BKP') IS NOT NULL
	DROP TABLE MAESTRO_BKP
GO
CREATE TABLE MAESTRO_BKP(
	id_bkp			INT				PRIMARY KEY IDENTITY(0,1),
	fecha_bkp		DATE			DEFAULT(GETDATE()),
	matricula		INT				NOT NULL,
	num_nomina		VARCHAR(25)		NOT NULL,
	nombre			VARCHAR(25)		NOT NULL,
	apellido_Pat	VARCHAR(25)		NOT NULL,
	apellido_Mat	VARCHAR(25)		NOT NULL,
	genero			BIT				DEFAULT(1),
	fecha_Naci		DATE			NULL,
	titulo			VARCHAR(50)		NULL,
)

IF OBJECT_ID('AULA_BKP') IS NOT NULL
	DROP TABLE AULA_BKP
GO
CREATE TABLE AULA_BKP(
	id_bkp			INT PRIMARY		KEY IDENTITY(0,1),
	fecha_bkp		DATE			DEFAULT(GETDATE()),
	id				INT				NOT NULL,
	cupo			INT				NOT NULL,
	localizacion	VARCHAR(255)	NULL
)--Entidad Debil para GRUPO

IF OBJECT_ID('GRUPO_BKP') IS NOT NULL
	DROP TABLE GRUPO_BKP
GO
CREATE TABLE GRUPO_BKP(
	id_bkp			INT		PRIMARY KEY IDENTITY(0,1),
	fecha_bkp		DATE	DEFAULT(GETDATE()),
	id				INT		NOT NULL,
	materia_fk		INT		NOT NULL,
	maestro_fk		INT		NOT NULL,
	aula_fk			INT		NOT NULL,
	semestre_fk		INT		NOT NULL
)

IF OBJECT_ID('ALUMNO_GRUPO_BKP') IS NOT NULL
	DROP TABLE ALUMNO_GRUPO_BKP
GO
CREATE TABLE ALUMNO_GRUPO_BKP(
	id_bkp				INT				PRIMARY KEY IDENTITY(0,1),
	fecha_bkp			DATE			DEFAULT(GETDATE()),

	id					INT				NOT NULL,
	calificacion		FLOAT			NULL,
	fecha_calif			DATE			NULL,
	grupo_fk			INT				NOT NULL,
	alumno_fk			INT				NOT NULL
)